#!/bin/bash

./tailwindcss -c tailwind.config.js -i www/asset/css/input.css -o www/asset/css/output.css --minify

version=$(cat ./.version)
sed -i -e "s/{{version}}/$version/g" www/worker.js
sed -i -e "s/{{version}}/$version/g" app/main.js
