[package]
name = "verbal"
version = "0.0.3-dev"
edition = "2018"

[dependencies]
ron = "*"
tide = "*"
rand = "*"
surf = "*"
regex = "*"
tide-sqlx = "*"
serde_json = "*"
tide-compress = "*"
serde = { version = "*", features = ["derive"] }
async-std = { version = "*", features = ["attributes", "tokio1"] }
sqlx = { version = "*", features = ["runtime-async-std-rustls", "postgres"] }

[[bin]]
name = "main"
path = "src/main.rs"

[[bin]]
name = "import"
path = "src/import.rs"

[[bin]]
name = "test"
path = "src/test.rs"
