#!/bin/bash

LIB_DIR="./www/asset/lib"
FONT_DIR="./www/asset/font"

echo "create $LIB_DIR"
mkdir -p "$LIB_DIR"
echo "create $FONT_DIR"
mkdir -p "$FONT_DIR"

# tailwindcss
echo "download tailwindcss"
curl -sL https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-linux-x64 -o "tailwindcss"
chmod +x tailwindcss

# vue
echo "download vue"
curl -sL https://cdn.jsdelivr.net/npm/vue@2/dist/vue.esm.browser.min.js -o "$LIB_DIR/vue.min.js"
# curl -L https://unpkg.com/vue@latest/dist/vue.esm-browser.prod.js -o ./www/asset/lib/vue.min.js -s

# tabler-icons
echo "download tabler-icons"
curl -sL https://cdn.jsdelivr.net/npm/@tabler/icons@latest/iconfont/tabler-icons.min.css -o "$LIB_DIR/tabler-icons.min.css"
sed -i -e "s/fonts\/tabler-icons/..\/font\/tabler-icons/g" "$LIB_DIR/tabler-icons.min.css"
echo "download tabler-icons font"
curl -sL https://cdn.jsdelivr.net/npm/@tabler/icons@latest/iconfont/fonts/tabler-icons.eot -o "$FONT_DIR/tabler-icons.eot"
curl -sL https://cdn.jsdelivr.net/npm/@tabler/icons@latest/iconfont/fonts/tabler-icons.ttf -o "$FONT_DIR/tabler-icons.ttf"
curl -sL https://cdn.jsdelivr.net/npm/@tabler/icons@latest/iconfont/fonts/tabler-icons.woff -o "$FONT_DIR/tabler-icons.woff"
curl -sL https://cdn.jsdelivr.net/npm/@tabler/icons@latest/iconfont/fonts/tabler-icons.woff2 -o "$FONT_DIR/tabler-icons.woff2"

# inter
echo "download inter font"
curl -sL https://fonts.google.com/download?family=Inter -o "$FONT_DIR/inter.zip"
unzip -qq "$FONT_DIR/inter.zip" -d "$FONT_DIR/inter"
mv "$FONT_DIR/inter/static/Inter-Regular.ttf" "$FONT_DIR/"
mv "$FONT_DIR/inter/static/Inter-Medium.ttf" "$FONT_DIR/"
mv "$FONT_DIR/inter/static/Inter-SemiBold.ttf" "$FONT_DIR/"
rm -rf "$FONT_DIR/inter"
rm -rf "$FONT_DIR/inter.zip"

echo "done"
