version: "3.9"
services:
  web:
    build:
      context: .
      args:
        - VERSION
    ports:
      - "4202:4202"
    volumes:
      - /home/andreas/.config/:/root/.config/:z
      - /etc/letsencrypt/:/etc/letsencrypt/:z
      - /home/andreas/git/verbal/media/:/home/andreas/git/verbal/media/:z
