version: "3.9"
services:
  web:
    build:
      context: .
      args:
        - VERSION
    ports:
      - "443:443"
    volumes:
      - /home/andreas/.config/:/root/.config/:z
      - /etc/letsencrypt/:/etc/letsencrypt/:z
